{% set version = "10.0.0" %}

package:
  name: llvmlib
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/llvm-10.0.0.src.tar.xz
    sha256: df83a44b3a9a71029049ec101fb0077ecbbdf5fe41e395215025779099a98fdf

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make 
    - python >=3
  host:
    - zlib

tests:
  commands:
    - $PREFIX/bin/llvm-config --libs
    - $PREFIX/bin/llc -version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM