{% set version = "10.0.1" %}

package:
  name: llvmlib
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/llvm-10.0.1.src.tar.xz
    sha256: c5d8e30b57cbded7128d78e5e8dad811bff97a8d471896812f57fa99ee82cdf3

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make 
    - python >=3
  host:
    - zlib

tests:
  commands:
    - $PREFIX/bin/llvm-config --libs
    - $PREFIX/bin/llc -version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM