{% set version = "9.0.1" %}

package:
  name: llvmlib
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz
    sha256: 00a1ee1f389f81e9979f3a640a01c431b3021de0d42278f6508391a2f0b81c9a

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make 
    - python >=3
  host:
    - zlib

tests:
  commands:
    - $PREFIX/bin/llvm-config --libs
    - $PREFIX/bin/llc -version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM