{% set version = "9.0.0" %}

package:
  name: llvmlib
  version: {{ version }}

source:
  - url: http://releases.llvm.org/{{ version }}/llvm-{{ version }}.src.tar.xz
    sha256: d6a0565cf21f22e9b4353b2eb92622e8365000a9e90a16b09b56f8157eabfe84

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make 
    - python >=3
  host:
    - zlib

tests:
  commands:
    - $PREFIX/bin/llvm-config --libs
    - $PREFIX/bin/llc -version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM