{% set name = "prettyprinter" %}
{% set version = "0.18.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9fe5da7ec53510881dd35d7a5c677ba45f34cfe6a8e78d1abd20652cf82139a8
  patches:
    - no_test_runner.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - colorful >=0.4.0
    - pip
    - pygments >=2.2.0
    - python
  run:
    - colorful >=0.4.0
    - pygments >=2.2.0
    - python

test:
  imports:
    - prettyprinter
    - prettyprinter.extras

about:
  home: "https://github.com/tommikaikkonen/prettyprinter"
  license: MIT
  license_family: MIT
  summary: "Syntax-highlighting, declarative and composable pretty printer for Python 3.5+"

