{% set name = "colorful" %}
{% set version = "0.5.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 86848ad4e2eda60cd2519d8698945d22f6f6551e23e95f3f14dfbb60997807ea

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - colorama # [win]
    - pip
    - python
  run:
    - colorama # [win]
    - python

test:
  imports:
    - colorful

about:
  home: "http://github.com/timofurrer/colorful"
  license: MIT
  license_family: MIT
  summary: "Terminal string styling done right, in Python."
