{% set git_hash = "17cd27da9b31ce9220e5b3bbf51ad56d8f4579a1" %}
# Bump this up by one when you change the hash above and
# reset to 0 when updating the version.
{% set revision = "1" %}
{% set release = False %}
{% set version = "0.7dev1" %}


{% if not release %}
  {% set version = version + "+" + revision + "." + git_hash[:8] %}
{% endif %}

package:
  name: tvm
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/tvm.git
  git_rev: {{ git_hash }}
  patches:
    - no_nvcc.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
  host:
    - python {{ python }}
    - cython
    - numpy
    - setuptools
    - decorator
    - tvm-libs =={{ version }}
  run:
    - python
    - psutil
    - {{ pin_compatible('numpy') }}
    - decorator
    - tvm-libs =={{ version }}

test:
  imports:
    - tvm
    - topi
  requires:
    - pytest
    - scipy
  source_files:
    - tests/python
  commands:
    - pytest -v tests/python/integration

about:
  home: https://github.com/dmlc/tvm
  license: Apache2
  summary: a low level domain specific language for compiling tensor computation pipelines
