{% set git_hash = "55aefc22a6a24ad21953b887f171eac75a33b825" %}
# Bump this up by one when you change the hash above and
# reset to 0 when updating the version.
{% set revision = "3" %}
{% set release = False %}
{% set version = "0.7dev1" %}

{% if not release %}
  {% set version = version + "+" + revision + "." + git_hash[:8] %}
{% endif %}

package:
  name: tvm-libs
  version: {{ version }}

source:
  git_url: https://github.com/apache/incubator-tvm.git
  git_rev: {{ git_hash }}

build:
  number: 0
  string: cuda{{ cuda_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda]

requirements:
  build:
    # The anaconda compilers for OS X are old an annoying
    # so we rely on the platform ones for now
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make
    - git
  host:
    - llvmlib ==10.0.0
    - zlib  # [linux]
  run:
    - {{ pin_compatible('cudatoolkit', lower_bound=cuda_version, max_pin='x.x') }}  # [cuda]
    - {{ pin_compatible('cudnn', lower_bound='7.6.0', max_pin='x') }}  # [cuda]

about:
  home: https://github.com/dmlc/tvm
  license: Apache2
  summary: a low level domain specific language for compiling tensor computation pipelines