{% set name = "antlr4-python3-runtime" %}
{% set version = "4.7.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 168cdcec8fb9152e84a87ca6fd261b3d54c8f6358f42ab3b813b14a7193bb50b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - typing
  run:
    - python
    - typing

test:
  imports:
    - antlr4
    - antlr4.atn
    - antlr4.dfa
    - antlr4.error
    - antlr4.tree
    - antlr4.xpath

about:
  home: "http://www.antlr.org"
  license: BSD
  license_family: BSD
  summary: "ANTLR 4.7.2 runtime for Python 3"
