{% set version = "1.1.0" %}

package:
  name: pytorch
  version: {{ version }}


source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v1.1.0


build:
  number: 0
  string: cuda{{ cuda_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python {{ python }}
    - numpy
    - setuptools
    - pyyaml
    - cffi
    - mkl >=2018
    - mkl-include
    - typing
    - ninja
    - magma-cuda{{ cuda_version | replace('.', '') }}  # [cuda]

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('mkl', lower_bound='2018', max_pin='') }}
    - cffi
    - ninja
    - {{ pin_compatible('cudatoolkit', lower_bound=cuda_version, max_pin='x.x') }}  # [cuda]
    - {{ pin_compatible('cudnn', lower_bound='7.6.0', max_pin='x') }}  # [cuda]


test:
 requires:
    - {{ compiler('cxx') }}
 imports:
    - torch
 source_files:
   - test
 commands:
   - OMP_NUM_THREADS=4 python ./test/run_test.py


about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
